### ISSUE TITLE
Bot parou de funcionar após nova atualização

### ISSUE THREAD

**Issue by rodrigoomuller** [newerton/bombcrypto-bot#128]
Esses erros aparecem na primeira vez que o bot tenta enviar heróis para trabalhar. Algo relacionado a casa (não possuo casa).

*******************************************************************************
** BOMBCRYPTO - BOT
**
** Please consider buying me a coffee :)
** BCOIN: 0x4847C29561B6682154E25c334E12d156e19F613a
** PIX: 08912d17-47a6-411e-b7ec-ef793203f836
*******************************************************************************
** Press CTRL + C to kill the bot.
** Some configs can be found in the https://github.com/newerton/bombcrypto-bot
*******************************************************************************

Versions
  Local
    App: 1.9.0
    Config File: 1.9.0
  GitHub
    App: 1.9.0
    Config File: 1.9.0

Press Enter to start the bot...

2022-04-04 10:06:29 - 🤖 Starting bot...
2022-04-04 10:06:33 - ✅ Terms and Service accepted in cache
2022-04-04 10:06:33 - 📱 Initializing Telegram...
2022-04-04 10:06:35 - 🧾  Multi account enabled
2022-04-04 10:06:37 - 🪟  Browser Active: Bombcrypto - Google Chrome
2022-04-04 10:06:40 - 🏢 Search for heroes to work
2022-04-04 10:06:45 - ⚒️ Sending heroes with green stamina bar to work!
Traceback (most recent call last):
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\index.py", line 50, in <module>
    main()
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\index.py", line 36, in main
    multi_account.start()
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\src\multi_account.py", line 53, in start
    self.botMultiAccount()
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\src\multi_account.py", line 112, in botMultiAccount
    self.activeWindow(last, window)
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\src\multi_account.py", line 199, in activeWindow
    self.steps(last)
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\src\multi_account.py", line 137, in steps
    self.heroes.getMoreHeroes()
  File "C:\Users\Rodrigo Muller\Downloads\bombcrypto-bot-main\src\heroes.py", line 103, in getMoreHeroes
    houseEnabled = self.accounts[account_active]['house']
KeyError: 'house'

**Comment by rodrigoomuller** [comment]
Este é meu config

app:
  theme: 'default'
  verify_version: true
  emoji: true
  terminal_colorful: true
  run_time_app: 1
  monitor_to_use: 1
  captcha: false
  speed: 'fast'
  authenticate: false
  multi_account:
    enable: true
    window_title: "bombcrypto"
    window_fullscreen: false

time_intervals:
  send_heroes_for_work: [25, 35]
  refresh_heroes_positions: [3, 5]

chests:
  values:
    chest_01: 0.008
    chest_02: 0.024
    chest_03: 0.128
    chest_04: 0.256

threshold:
  default: 0.7
  error_message: 0.7
  back_button: 0.9
  work_button: 0.9
  home_enable_button: 0.98
  heroes_green_bar: 0.9
  heroes_red_bar: 0.9
  heroes_full_bar: 0.9
  heroes_send_all: 0.9
  heroes_rest_all: 0.9
  chest: 0.65
  jail: 0.8
  auth_input: 0.9
  heroes:
    common: 0.8
    rare: 0.8
    super_rare: 0.8
    epic: 0.8
    legend: 0.8
    super_legend: 0.8

heroes:
  mode: 'green'
  list:
    scroll_attempts: 3

offsets:
  work_button_green: [120, 140]
  work_button_full: [90, 110]
  house_button: [260, 280]

metamask:
  enable: false
  password: ""

services:
  telegram: true

log:
  save_to_file: false
  console: false
  show_print: false

**Comment by newerton** [comment]
@rodrigoomuller Atualizou o accounts.yaml?
