### ISSUE TITLE
Problemas Versão 1.9.0

### ISSUE THREAD

**Issue by rodrigotiss** [newerton/bombcrypto-bot#131]
Não estou conseguindo utilizar o bot na versão 1.9.0 apresenta o erro abaixo, analisei todas as linhas do multi account e nao identifiquei nada que possa estar apresentando problemas.

Versions
  Local
    App: 1.9.0
    Config File: 1.9.0
  GitHub
    App: 1.9.0
    Config File: 1.9.0

Press Enter to start the bot...

2022-04-05 15:36:07 - 🤖 Starting bot...
2022-04-05 15:36:11 - ✅ Terms and Service accepted in cache
2022-04-05 15:36:11 - 📱 Initializing Telegram...
2022-04-05 15:36:13 - 🧾 Multi account enabled
Traceback (most recent call last):
  File "C:\bomb teste 1.90\index.py", line 50, in <module>
    main()
  File "C:\bomb teste 1.90\index.py", line 36, in main
    multi_account.start()
  File "C:\bomb teste 1.90\src\multi_account.py", line 53, in start
    self.botMultiAccount()
  File "C:\bomb teste 1.90\src\multi_account.py", line 89, in botMultiAccount
    total_accounts = len(self.accounts)
TypeError: object of type 'NoneType' has no len()

**Comment by newerton** [comment]
@rodrigotiss Se não me engano soltei uma correção ontem ou antes de ontem.

Verifica se no seu multi_account.py na linha 17, contèm esse variavel aqui:

https://github.com/newerton/bombcrypto-bot/blob/main/src/multi_account.py#L17
