### ISSUE TITLE
socket.gaierror: [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by yokosogithub** [newerton/bombcrypto-bot#153]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001A8A1838EB0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /newerton/bombcrypto-bot/main/config/version.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A8A1838EB0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/bombcrypto-bot/index.py", line 51, in <module>
    main()
  File "C:/Users/Administrator/Desktop/bombcrypto-bot/index.py", line 35, in main
    application.start()
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\src\application.py", line 29, in start
    self.compareYamlConfig()
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\src\application.py", line 134, in compareYamlConfig
    gitHubVersion = self.gitHubVersion()
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\src\application.py", line 87, in gitHubVersion
    data = requests.get(
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\Desktop\bombcrypto-bot\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /newerton/bombcrypto-bot/main/config/version.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A8A1838EB0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
python-BaseException

**Comment by newerton** [comment]
Are you instantiating the bot multiple times, are you using forever.py?

If using forever.py, the bot will loop if an error occurs. And the bot requests to that address: https://raw.githubusercontent.com/newerton/bombcrypto-bot/main/config/version.yaml

This error that occurred is because the bot made too many requests to the github address.

**Comment by yokosogithub** [comment]
nope，I only open one robot

发自我的iPhone
