### ISSUE TITLE
Erro ao iniciar "Start" 

### ISSUE THREAD

**Issue by RHENOFFICE** [newerton/bombcrypto-bot#158]
Já faz a algum tempo que estou tendo esse erro e já fiz de tudo um pouco incluindo formatar o PC e fazer tudo do zero mas o erro permanece como proceder?

Press Enter to start the bot...

2022-05-12 20:29:03 - 🤖 Starting bot...
Traceback (most recent call last):
  File "C:\BOTs\bombcrypto-bot-main\index.py", line 51, in <module>
    main()
  File "C:\BOTs\bombcrypto-bot-main\index.py", line 35, in main
    application.start()
  File "C:\BOTs\bombcrypto-bot-main\src\application.py", line 36, in start
    self.signTheTerm()
  File "C:\BOTs\bombcrypto-bot-main\src\application.py", line 186, in signTheTerm
    if self.actions.clickButton(checkbox_terms_and_service):
  File "C:\BOTs\bombcrypto-bot-main\src\actions.py", line 47, in clickButton
    matches = self.recognition.positions(image, threshold=threshold)
  File "C:\BOTs\bombcrypto-bot-main\src\recognition.py", line 44, in positions
    if self.config['log']['show_print'] is not False:
KeyError: 'show_print'
Starting bot with infinite execution!

**Comment by newerton** [comment]
Você criou o arquivo config.yaml?

**Comment by RHENOFFICE** [comment]
Eu sou mesmo um asno... Achei o erro eu tinha baixado a nova versão mas acabei mantendo a pasta Config da versão anterior e não tinha visto que avia modificações na nova!

RESOLVIDO agradeço a ajuda!
