### ISSUE TITLE
Update 2.0.6

### ISSUE THREAD

**Issue by veenx67** [newerton/bombcrypto-bot#198]
Depois da atualização, o bot começou a exibir esse erro.
Com a versão 2.0.5 funciona perfeitamente

Traceback (most recent call last):
  File ".\index.py", line 30, in <module>
    multi_account = MultiAccount()
  File "C:\bot2\src\multi_account.py", line 18, in __init__
    self.accounts = Config().accounts()
  File "C:\bot2\src\config.py", line 40, in accounts
    return yaml.safe_load(stream)
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Bot\AppData\Local\Programs\Python\Python38\lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 4, column 1:
    1: {
    ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 11, column 3:
      2: {
      ^

**Comment by newerton** [comment]
Config the accounts.yaml

https://github.com/newerton/bombcrypto-bot/blob/main/config/EXAMPLE-accounts.yaml

**Comment by veenx67** [comment]
![image](https://user-images.githubusercontent.com/90722789/172925927-3f650f53-2c93-486f-b96f-82c4bf380f47.png)

  
  Eu configurei, tem alguma coisa faltando? alguma virgula? só tirei os dados da conta

**Comment by newerton** [comment]
Se você deixar 1 conta, funciona?

**Comment by newerton** [comment]
Tira essas virgulas da linha 10 e 18, que está depois da chave.

**Comment by veenx67** [comment]
> Tira essas virgulas da linha 10 e 18, que está depois da chave.

era as virgulas o problema. vlw

aproveitando aqui, a opção pra não deixar em full screen não funciona com multi account?

**Comment by newerton** [comment]
O bot sempe vai deixar o navegador em fullscreen! O bot faz reconhecimento por imagens, se no momento do reconhecimento, o bot encontrar 4 botões de voltar (3 contas), qual ele vai clicar?

**Comment by veenx67** [comment]
> O bot sempe vai deixar o navegador em fullscreen! O bot faz reconhecimento por imagens, se no momento do reconhecimento, o bot encontrar 4 botões de voltar (3 contas), qual ele vai clicar?

faz sentido, não tinha pensando nisso lol

obrigado.
