### ISSUE TITLE
Mapa novo

### ISSUE THREAD

**Issue by veenx67** [newerton/bombcrypto-bot#200]
2022-06-10 17:53:36 - ⏳ Wait for 5 seconds, to show your TOKENS
2022-06-10 17:53:42 - 🪟 Your Chest image created
Traceback (most recent call last):
File ".\index.py", line 51, in
main()
File ".\index.py", line 37, in main
multi_account.start()
File "C:\bot\src\multi_account.py", line 54, in start
self.botMultiAccount()
File "C:\bot\src\multi_account.py", line 113, in botMultiAccount
self.activeWindow(last, window)
File "C:\bot\src\multi_account.py", line 202, in activeWindow
self.steps(last)
File "C:\bot\src\multi_account.py", line 148, in steps
self.game.clickNewMap()
File "C:\bot\src\game.py", line 53, in clickNewMap
self.tokens.getSens()
File "C:\bot\src\tokens.py", line 33, in getSens
cropped = image[y:y+h, x:x+w]
TypeError: 'NoneType' object is not subscriptable
Starting bot with infinite execution!

O bot da erro, ai tem que fechar e abrir denovo

Ja aconteceu com 10 mapas, somente com a versão 2.0.6

**Comment by newerton** [comment]
?

**Comment by Pygew** [comment]
> 2022-06-10 17:53:36 - ⏳ Wait for 5 seconds, to show your TOKENS
> 2022-06-10 17:53:42 - 🪟 Your Chest image created
> Traceback (most recent call last):
> File ".\index.py", line 51, in
> main()
> File ".\index.py", line 37, in main
> multi_account.start()
> File "C:\bot\src\multi_account.py", line 54, in start
> self.botMultiAccount()
> File "C:\bot\src\multi_account.py", line 113, in botMultiAccount
> self.activeWindow(last, window)
> File "C:\bot\src\multi_account.py", line 202, in activeWindow
> self.steps(last)
> File "C:\bot\src\multi_account.py", line 148, in steps
> self.game.clickNewMap()
> File "C:\bot\src\game.py", line 53, in clickNewMap
> self.tokens.getSens()
> File "C:\bot\src\tokens.py", line 33, in getSens
> cropped = image[y:y+h, x:x+w]
> TypeError: 'NoneType' object is not subscriptable
> Starting bot with infinite execution!

Eu não sei o que eu fiz, mas eu editei o comentario.

Ja aconteceu com 10 mapas, somente com a versão 2.0.6

**Comment by Pygew** [comment]
Tem algum modo de eu pegar um log mais completo?
