### ISSUE TITLE
Mapa novo

### ISSUE THREAD

**Issue by veenx67** [newerton/bombcrypto-bot#205]
Bom dia, sempre que o mapa termina, acontece isso.

> 2022-06-18 01:34:17 - Wait for 5 seconds, to show your TOKENS
> 2022-06-18 01:34:22 - Your Chest image created
> Traceback (most recent call last):
>   File "C:\bot\index.py", line 51, in <module>
>     main()
>   File "C:\bot\index.py", line 37, in main
>     multi_account.start()
>   File "C:\bot\src\multi_account.py", line 55, in start
>     self.botMultiAccount()
>   File "C:\bot\src\multi_account.py", line 114, in botMultiAccount
>     self.activeWindow(last, window)
>   File "C:\bot\src\multi_account.py", line 203, in activeWindow
>     self.steps(last)
>   File "C:\bot\src\multi_account.py", line 149, in steps
>     self.game.clickNewMap()
>   File "C:\bot\src\game.py", line 62, in clickNewMap
>     self.tokens.getSens()
>   File "C:\bot\src\tokens.py", line 33, in getSens
>     cropped = image[y:y+h, x:x+w]
> TypeError: 'NoneType' object is not subscriptable
> Starting bot with infinite execution!

**Comment by newerton** [comment]
Está usando multi account? Verifica se ele está abrindo o seu bau para verificar a quantidade de SENS que você tem.

**Comment by veenx67** [comment]
sim, multi account; ele clica no botão do novo mapa, e vai pro bau, quando ele fecha o bau o crash vem

**Comment by newerton** [comment]
@Pygew Vou testar aqui, está usando Windows ou Linux?

No seu projeto tem uma pasta com o nome de "temp", outra dúvida, está usando o serviço do Telegram?

**Comment by veenx67** [comment]
Estou usando no Windows 10 versão 19044.1766

Sim, tem a pasta temp, com 2 arquivos dentro ".gitignore" e "tokens-box.png" 

O telegram esta desativado.
