### ISSUE TITLE
Erro ao encontrar erro

### ISSUE THREAD

**Issue by ruanzxto** [newerton/bombcrypto-bot#40]
2022-01-18 02:03:00 - 💥 Error detected, trying to resolve
Traceback (most recent call last):
  File "/home/bomb/Downloads/newbot/index.py", line 50, in <module>
    main()
  File "/home/bomb/Downloads/newbot/index.py", line 36, in main
    multi_account.start()
  File "/home/bomb/Downloads/newbot/src/multi_account.py", line 56, in start
    self.botSingle()
  File "/home/bomb/Downloads/newbot/src/multi_account.py", line 75, in botSingle
    self.steps(last)
  File "/home/bomb/Downloads/newbot/src/multi_account.py", line 125, in steps
    self.errors.verify()
  File "/home/bomb/Downloads/newbot/src/error.py", line 32, in verify
    self.telegram.commandSendPrint()
TypeError: commandSendPrint() missing 1 required positional argument: 'update'

![image](https://user-images.githubusercontent.com/97133292/149861702-951d2f1f-adc6-41c5-8ea1-6a1b2006dd54.png)

**Comment by newerton** [comment]
@ruanzxto Atualiza seu bot, ele já está na versão 1.5.7. E foi feita essa correção.

**Comment by ruanzxto** [comment]
Deu certo!
